" =============================================================================
"      FileName: .vimrc
"        Author: marslo.jiao@gmail.com
"       Created: 2010-10
"       Version: 0.0.27
"    LastChange: 2023-12-21 00:02:14
" =============================================================================

set nocompatible
set maxmempattern=5000
set history=1000
set diffopt=filler,context:3
set spell spelllang=en_us
set spellcapcheck=1
set spellfile=~/.vim/spell/en.utf-8.add
set lazyredraw
set shell=/usr/local/bin/bash
runtime macros/matchit.vim

let performance_mode = 1
set fileformat=unix
set fileformats=unix
set nowrap                                                          " no wrap lines
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/cache/.viminfo
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set tags=tags

if empty( glob('~/.vim/cache/') ) | execute 'silent !mkdir -p ~/.vim/cache' | endif
if empty( glob('~/.vim/undo/')  ) | execute 'silent !mkdir -p ~/.vim/undo'  | endif

" /**************************************************************
"                                  _
"  _ __  _ __ ___  _ __   ___ _ __| |_ _   _
" | '_ \| '__/ _ \| '_ \ / _ \ '__| __| | | |
" | |_) | | | (_) | |_) |  __/ |  | |_| |_| |
" | .__/|_|  \___/| .__/ \___|_|   \__|\__, |
" |_|             |_|                  |___/
"
" **************************************************************/
let bud         = expand( '~/.vim/bundle' ) . '/'
let mapleader   = ","
let g:mapleader = ","

" bundle
filetype off
set rtp+=~/.vim/bundle/snipmate.vim/snippets/
set rtp+=~/.vim/bundle/Vundle.vim/
set rtp+=/usr/local/opt/fzf                                         " $ brew install fzf
call vundle#begin()
" call vundle#rc()

Plugin 'VundleVim/Vundle.vim'
" Plugin 'gmarik/vundle.git'
Plugin 'tpope/vim-pathogen'
Plugin 'tpope/vim-surround'
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-repeat'
Plugin 'Yggdroot/indentLine'
Plugin 'kien/ctrlp.vim'
Plugin 'sjl/gundo.vim'
Plugin 'preservim/tagbar'
Plugin 'marslo/authorinfo'
Plugin 'marslo/auto-pairs'
Plugin 'tomtom/tlib_vim'
Plugin 'yegappan/mru'
Plugin 'grep.vim'
Plugin 'LargeFile'
Plugin 'Konfekt/FastFold'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'vim-autoformat/vim-autoformat'
Plugin 'tpope/vim-fugitive'                                         " ╮
Plugin 'mbbill/undotree'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'ycm-core/lsp-examples'
Plugin 'tpope/vim-commentary'
" Plugin 'marslo/EnhCommentify.vim'
Plugin 'marcweber/vim-addon-mw-utils'
Plugin 'marslo/snipmate.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'marslo/MarsloFunc'
Plugin 'L9'
" Plugin 'mhinz/vim-signify'
" Plugin 'wsdjeg/vim-fetch'
Plugin 'rhysd/vim-grammarous'
Plugin 'dpelle/vim-LanguageTool'
" markdown
Plugin 'preservim/vim-markdown'                                     " markdown
Plugin 'valloric/MatchTagAlways'                                    " web design
" Plugin 'gabrielelana/vim-markdown'
" Plugin 'tpope/vim-markdown'
" Plugin 'junegunn/vim-easy-align'
" git
Plugin 'tpope/vim-fugitive'                                         " ╮
Plugin 'airblade/vim-gitgutter'                                     " │
Plugin 'APZelos/blamer.nvim'                                        " ├ git
Plugin 'tpope/vim-git'                                              " │
Plugin 'zivyangll/git-blame.vim'                                    " ╯
" ansible
Plugin 'pearofducks/ansible-vim'
" python
" Plugin 'python-mode/python-mode'
Plugin 'Vimjas/vim-python-pep8-indent'
Plugin 'python_fold'
Plugin 'pyflakes/pyflakes'
Plugin 'python_match.vim'
Plugin 'vim-python/python-syntax'
Plugin 'davidhalter/jedi-vim'
" Plugin 'mfukar/robotframework-vim'
" github page
Plugin 'parkr/vim-jekyll'
" Web design
" Plugin 'jaxbot/browserlink.vim'
" colors and themes and syntax
Plugin 'morhetz/gruvbox'                                            " theme
Plugin 'luochen1990/rainbow'                                        " ╮ color
Plugin 'marslo/vim-coloresque'                                      " ╯ 'ap/vim-css-color'
Plugin 'amadeus/vim-css'
" Plugin 'ap/vim-css-color'
Plugin '907th/vim-auto-save'
Plugin 'txt.vim'
Plugin 'marslo/vim-coloresque'
Plugin 'marslo/marslo.vim'
Plugin 'marslo/MarsloVimOthers'
Plugin 'altercation/vim-colors-solarized'
" yaml
Plugin 'stephpy/vim-yaml'                                           " ╮
Plugin 'pedrohdz/vim-yaml-folds'                                    " ├ yaml
Plugin 'dense-analysis/ale'                                         " ╯
" groovy
Plugin 'modille/groovy.vim'                                         " /usr/local/vim/share/vim/vim90/syntax/groovy.vim
Plugin 'vim-scripts/vim-gradle'
Plugin 'marslo/Jenkinsfile-vim-syntax'                              " jenkinfile
" Plugin 'keith/cocoapods.vim'
" dockerfile
Plugin 'ekalinin/Dockerfile.vim'                                    " dockerfile
" others
" Plugin 'ianva/vim-youdao-translater'
Plugin 'rizzatti/dash.vim'

call vundle#end()
call pathogen#infect()
filetype plugin indent on
syntax enable on

" /**************************************************************
"   __                  _   _
"  / _|_   _ _ __   ___| |_(_) ___  _ __
" | |_| | | | '_ \ / __| __| |/ _ \| '_ \
" |  _| |_| | | | | (__| |_| | (_) | | | |
" |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|
"
" **************************************************************/
function! GetVundle()                                               " GetVundle() inspired by: http://pastebin.com/embed_iframe.php?i=C9fUE0M3
  let vundleAlreadyExists=1
  if has( 'win32' ) || has( 'win64' )
    let bud=$VIM . '\bundle'
    let vud=bud . '\Vundle.vim'
    let vudcfg=expand(vud . '\.git\config')
  else
    let bud='~/.vim/bundle'
    let vud=bud . '/Vundle.vim'
    let vudcfg=expand(vud . '/.git/config')
  endif

  if filereadable(vudcfg)
    echo "Vundle has existed at " . expand(vud)
  else
    echo "Installing Vundle..."
    echo ""
    if isdirectory(expand(bud)) == 0
      call mkdir(expand(bud), 'p')
    endif
    execute 'silent !git clone https://github.com/VundleVim/Vundle.vim.git "' . expand(vud) . '"'
    let vundleAlreadyExists=0
  endif
endfunction
command! GetVundle :call GetVundle()

function! DoRedraw()
  execute "silent redraw!"
endfunction
nnoremap <M-l> :call DoRedraw()<CR>
noremap <D-l>  :call DoRedraw()<CR>

if has( 'unix' ) || has( 'macunix' )
  if empty( glob('~/.vim/bundle/Vundle.vim') ) || empty( glob($VIM . '\bundle\Vundle.vim') )
    execute 'silent exec "GetVundle"'
  endif
endif

function! ToggleVerbose()
  if !&verbose
    set verbosefile=~/.log/vim/verbose.log
    set verbose=15
  else
    set verbose=0
    set verbosefile=
  endif
endfunction
command! ToggleVerbose :call ToggleVerbose()

function! ToggleWindowHorizontalVerticalSplit()
  if !exists( 't:splitType' )
    let t:splitType = 'vertical'
  endif

  if t:splitType == 'vertical'                                      " is vertical switch to horizontal
    windo wincmd K
    let t:splitType = 'horizontal'
  else                                                              " is horizontal switch to vertical
    windo wincmd H
    let t:splitType = 'vertical'
  endif
endfunction
nnoremap <silent> <leader>wt :call ToggleWindowHorizontalVerticalSplit()<cr>

function! GetFiletypes()
  " https://vi.stackexchange.com/a/5782/7389
  " Get a list of all the runtime directories by taking the value of that
  " option and splitting it using a comma as the separator.
  let rtps      = split( &runtimepath, "," )
  " This will be the list of filetypes that the function returns
  let filetypes = []

  " Loop through each individual item in the list of runtime paths
  for rtp in rtps
    let syntax_dir = rtp . "/syntax"
    " Check to see if there is a syntax directory in this runtimepath.
    if ( isdirectory(syntax_dir) )
      " Loop through each vimscript file in the syntax directory
      for syntax_file in split( glob(syntax_dir . "/*.vim"), "\n" )
        " Add this file to the filetypes list with its everything
        " except its name removed.
        call add( filetypes, fnamemodify(syntax_file, ":t:r") )
      endfor
    endif
  endfor

  " This removes any duplicates and returns the resulting list.
  " NOTE: This might not be the best way to do this, suggestions are welcome.
  return uniq( sort(filetypes) )
endfunction

if isdirectory( expand(bud . 'MarsloFunc') )
  command! GetVim :call marslofunc#GetVim()<CR>
  nnoremap cmd    :call marslofunc#OpenCMD()<CR>
  nnoremap gf     :call marslofunc#GotoFile()<CR>
  xnoremap *      :<C-u>call marslofunc#VSetSearch()<CR>/<C-R>=@/<CR><CR>
  xnoremap #      :<C-u>call marslofunc#VSetSearch()<CR>?<C-R>=@/<CR><CR>
  noremap  <M-o>  :call marslofunc#OpenFoler()<CR>
  nnoremap <F12>  :call marslofunc#UpdateTags()<CR>
  nnoremap <C-F5> :call marslofunc#RunResult()<CR>
  nnoremap <leader>ti :call marslofunc#callit()<CR>

  augroup resCur
    autocmd!
    autocmd BufWinEnter * call marslofunc#ResCur()
  augroup END

  set foldtext=v:folddashes.substitute(getline(v:foldstart),'/\\*\\\|\\*/\\\|{{{\\d\\=','','g')
  set foldtext=marslofund#MyFoldText()<CR>
endif

" twiddle case : https://vim.fandom.com/wiki/Switching_case_of_characters#Twiddle_case
function! TwiddleCase(str)
  if a:str ==# toupper( a:str )
    let result = tolower( a:str )
  elseif a:str ==# tolower( a:str )
    let result = substitute( a:str,'\(\<\w\+\>\)', '\u\1', 'g' )
  else
    let result = toupper( a:str )
  endif
  return result
endfunction
vnoremap ~ y:call setreg('', TwiddleCase(@"), getregtype(''))<CR>gv""Pgv

" spell
" set spellcamelcase=1
" ignore CamelCase words when spell checking
function! IgnoreSpells()                                            " ignore CamelCase words when spell checking
  syntax      match   CamelCase /\<[A-Z][a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syntax      cluster Spell add=CamelCase
  syntax      match   mixedCase /\<[a-z]\+[A-Z].\{-}\>/      contains=@NoSpell transparent
  syntax      cluster Spell add=mixedCase
  " or syntax match   myExNonWords +\<\p*[^A-Za-z \t]\p*\>+  contains=@NoSpell
  " or syntax match   myExCapitalWords +\<\w*[A-Z]\K*\>\|'s+ contains=@NoSpell
  " syntax    match   Url "\w\+:\/\/[:/?#[\]@!$&'()*+,;=0-9[:lower:][:upper:]_\-.~]\+" contains=@NoSpell containedin=@AllSpell transparent
  " syntax    cluster Spell add=Url
  " syntax    match   UrlNoSpell '\w\+:\/\/[^[:space:]]\+'   contains=@NoSpell transparent
  " syntax    cluster Spell add=UrlNoSpell
endfunction
autocmd BufRead,BufNewFile * :call IgnoreSpells()
set spellcapcheck=                                                  " ignore capital check

" redir into new tab: https://vim.fandom.com/wiki/Capture_ex_command_outputhttps://vim.fandom.com/wiki/Capture_ex_command_output
" `gt`, `:tabfirst`, `:tabnext`, `:tablast` ... to switch tabs : https://vim.fandom.com/wiki/Alternative_tab_navigation
function! TabMessage(cmd)
  redir => message
  silent execute a:cmd
  redir END
  if empty( message )
    echoerr "no output"
  else
    tabnew                                                          " use `new` instead of `tabnew` below if you prefer split windows instead of tabs
    setlocal buftype=nofile bufhidden=wipe noswapfile nobuflisted nomodified
    silent put=message
  endif
endfunction
command! -nargs=+ -complete=command TabMessage call TabMessage(<q-args>)

function! BSkipQuickFix(command)                                    " switch avoid quickfix : https://vi.stackexchange.com/a/19420/7389
  let start_buffer = bufnr('%')
  execute a:command
  while &buftype ==# 'quickfix' && bufnr('%') != start_buffer
    execute a:command
  endwhile
endfunction
nnoremap <Tab>      :call BSkipQuickFix("bn")<CR>
nnoremap <S-Tab>    :call BSkipQuickFix("bp")<CR>
nnoremap <leader>bp :call BSkipQuickFix("bn")<CR>
nnoremap <leader>bn :call BSkipQuickFix("bp")<CR>

" set spellcamelcase=1
fun! IgnoreCamelCaseSpell()                                         " Ignore CamelCase words when spell checking
  syn match CamelCase /\<[A-Z][a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syn match mixedCase /\<[a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syn cluster Spell add=CamelCase
  syn cluster Spell add=mixedCase
endfun
autocmd BufRead,BufNewFile * :call IgnoreCamelCaseSpell()
syn match UrlNoSpell '\w\+:\/\/[^[:space:]]\+' contains=@NoSpell

function! TriggerYCM()
  if g:loaded_youcompleteme == 1
    let g:loaded_youcompleteme = 0
  else
    let g:loaded_youcompleteme = 1
  endif
endfunction
nnoremap <C-y> :call TriggerYCM()<CR>

command! -nargs=0 DocToc execute 'silent !/usr/local/bin/doctoc --github --maxlevel 3 %' | execute 'redraw!'
command! -nargs=1 -range TabFirst exec <line1> . ',' . <line2> . 'Tabularsze /^[^' . escape(<q-args>, '\^$.[?*~') . ']*\zs' . escape(<q-args>, '\^$.[?*~')

" /**************************************************************
"                                                      _
"  _ __  _ __ ___   __ _ _ __ __ _ _ __ ___  _ __ ___ (_)_ __   __ _
" | '_ \| '__/ _ \ / _` | '__/ _` | '_ ` _ \| '_ ` _ \| | '_ \ / _` |
" | |_) | | | (_) | (_| | | | (_| | | | | | | | | | | | | | | | (_| |
" | .__/|_|  \___/ \__, |_|  \__,_|_| |_| |_|_| |_| |_|_|_| |_|\__, |
" |_|              |___/                                       |___/
"
" **************************************************************/

" Programming configs for Python
if has( "autocmd" )
  autocmd FileType python syn keyword pythonDecorator print self
  autocmd FileType python set tabstop=4 softtabstop=4 shiftwidth=4
  autocmd FileTYpe python set isk-=.
  " set textwidth=80
endif
let python_highlight_all = 1                                        " syntax-python

" python-mode configurations
if isdirectory( expand(bud . 'python-mode') ) || has('python3')
  nnoremap <leader>p :PymodeLint<CR>                                " trigger pymodelint by manual
  let g:pymode_python                     = '/usr/local/bin/python3'
  let g:pymode                            = 1                       " 1: turn on python-mode plugin
  let g:pymode_syntax_all                 = 1
  let g:pymode_warnings                   = 0                       " turn off plugin's warnings
  let g:pymode_folding                    = 1
  let g:pymode_options_colorcolumn        = 1
  let g:pymode_trim_whitespaces           = 1                       " trim unused white spaces on save
  let g:pymode_lint                       = 1                       " turn on code checking
  let g:pymode_lint_checkers              = ['pyflakes', 'pep8', 'mccabe']
  let g:pymode_lint_ignore                = "E111,E114,E501,W0611,E266" " E501: long line; E111&E114: 4 spaces indent; E266: too many # for comments
  let g:pymode_options                    = 0
  let g:pymode_rope                       = 0
  let g:pymode_indent                     = 0
  let g:pymode_syntax_highlight_self      = g:pymode_syntax_all
  let g:pymode_quickfix_minheight         = 3
  let g:pymode_quickfix_maxheight         = 3
  let g:python_check_syntax               = 0                       " disable check python script syntax on every save
  let g:pymode_lint_on_write              = 0                       " disable on save checking
  " let g:pymode_rope_regenerate_on_write = 0
  let g:pymode_lint_unmodified            = 1
  let g:pymode_indent                     = 1
endif

" /**************************************************************
"                                                _
"                                               | |
"   ___ ___  _ __ ___  _ __ ___   __ _ _ __   __| |___
"  / __/ _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|
" | (_| (_) | | | | | | | | | | | (_| | | | | (_| \__ \
"  \___\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/
"
" **************************************************************/
" reverse the lines of the whole file or a visually highlighted block.
    " :Rev is a shorter prefix you can use.
    " Adapted from http://tech.groups.yahoo.com/group/vim/message/34305
    " reference : https://superuser.com/a/387869/112396
command! -nargs=0 -bar -range=% Reverse
    \       let save_mark_t = getpos("'t")
    \<bar>      <line2>kt
    \<bar>      exe "<line1>,<line2>g/^/m't"
    \<bar>  call setpos("'t", save_mark_t)
nnoremap <Leader>r :Reverse <bar> nohlsearch<CR>
xnoremap <Leader>r :Reverse <bar> nohlsearch<CR>

command! -nargs=0 DocToc execute 'silent !/usr/local/bin/doctoc --github --maxlevel 3 %' | execute 'redraw!'
command! -nargs=1 First exec 'Tabularize /^[^' . escape(<q-args>, '\^$.[?*~') . ']*\zs' . escape(<q-args>, '\^$.[?*~')
command! -nargs=1 -range First exec <line1> . ',' . <line2> . 'Tabularize /^[^' . escape(<q-args>, '\^$.[?*~') . ']*\zs' . escape(<q-args>, '\^$.[?*~')

" /**************************************************************
"  _       _             __                     __  _   _
" (_)_ __ | |_ ___ _ __ / _| __ _  ___ ___     / / | |_| |__   ___ _ __ ___   ___
" | | '_ \| __/ _ \ '__| |_ / _` |/ __/ _ \   / /  | __| '_ \ / _ \ '_ ` _ \ / _ \
" | | | | | ||  __/ |  |  _| (_| | (_|  __/  / /   | |_| | | |  __/ | | | | |  __/
" |_|_| |_|\__\___|_|  |_|  \__,_|\___\___| /_/     \__|_| |_|\___|_| |_| |_|\___|
"
" **************************************************************/
if has('gui_running')
  set go=                                                           " hide everything (go = guioptions)
  set cpoptions+=n
  set guifont=Rec\ Mono\ Casual:h24
  " set guifont=Comic\ Mono:h26
  " set guifont=Ubuntu\ Mono:h26
  " set guifontwide=NSimsun:h16
  set renderoptions=type:directx,renmode:5
  set lines=30                                                      " the initialize size
  set columns=106
endif

if exists( '$TMUX' )         | set term=screen-256color | endif
if 'xterm-256color' == $TERM | set t_Co=256             | endif

if has( 'gui_running' ) || 'xterm-256color' == $TERM
  set background=dark
  let psc_style='cool'

  " colorscheme marslo                                              " marslo
  colorscheme gruvbox                                               " gruvbox

  """ terminal : `:help terminal-info`
  set term=xterm
  let &t_AB="\e[48;5;%dm"
  let &t_AF="\e[38;5;%dm"
  let &t_Co=256
  set t_Co=256
  "" italic
  let &t_ZH = "\e[3m"
  let &t_ZR = "\e[23m"

  """ solarized
  " colorscheme solarized
  " set termguicolors
  " let g:solarized_termcolors=256
  " let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
  " let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
  " let g:solarized_termtrans = 1
  " let g:solarized_extra_hi_groups = 1
  " let g:solarized_visibility = "high"
  " let g:solarized_contrast = "high"
  " let s:base03 = "255"
else
  set t_Co=8
  set t_Sb=^[[4%dm
  set t_Sf=^[[3%dm
  colorscheme marslo16
endif

"" cursor settings:                                                 " https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes0
"    block        : 1 -> blinking block        |  2 -> solid block
"    underscore   : 3 -> blinking underscore   |  4 -> solid underscore
"    vertical bar : 5 -> blinking vertical bar |  6 -> solid vertical bar
if $TERM_PROGRAM =~ "iTerm"
  let &t_SI = "\<Esc>]50;CursorShape=4\x7"                          " solid underscore for INSERT MODE
  let &t_SR = "\<Esc>]50;CursorShape=2\x7"                          " solid block for REPLACE MODE
  let &t_EI = "\<Esc>]10;CursorShape=3\x7"                          " blinking underscore for NORMAL MODE
else
  let &t_SI.="\e[4 q"                                               " SI = INSERT mode
  let &t_SR.="\e[4 q"                                               " SR = REPLACE mode
  let &t_EI.="\e[3 q"                                               " EI = NORMAL mode (ELSE)
endif

" /**************************************************************
"           _   _   _
"  ___  ___| |_| |_(_)_ __   __ _
" / __|/ _ \ __| __| | '_ \ / _` |
" \__ \  __/ |_| |_| | | | | (_| |
" |___/\___|\__|\__|_|_| |_|\__, |
"                           |___/
"
" **************************************************************/
set ttimeout
set ttimeoutlen=1
set ttyfast                                                         " enable fast terminal connection.
set clipboard+=unnamed                                              " copy the content to system clipboard by using y/p
set clipboard+=unnamedplus
set iskeyword-=.
set autochdir
set encoding=utf-8                                                  " input chinese (=cp936)
set termencoding=utf-8
let &termencoding=&encoding
set fileencoding=utf-8
set fileencodings=utf-8,latin1,ucs-bom,gbk,cp936,gb2312,gb18030     " code format
scriptencoding utf-8                                                " set after encoding
set rop=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1
set selection=exclusive                                             " mouse settings
set selectmode=mouse,key
set nobackup noswapfile nowritebackup noundofile noendofline nobuflisted
set number                                                          " line number
set report=0
set autoread                                                        " set auto read when a file is changed by outside
set showmatch                                                       " show matching bracets (shortly jump to the other bracets)
set matchtime=1                                                     " the shortly time
set tabstop=2                                                       " tab width
set softtabstop=2                                                   " width for backspace
set shiftwidth=2                                                    " the tab width by using >> & <<
set autoindent smartindent expandtab
set cindent
set cinoptions=(0,u0,U0
set smarttab                                                        " smarttab: the width of <Tab> in first line would refer to 'shiftwidth' parameter
set linebreak
set modifiable
set write
set incsearch hlsearch ignorecase smartcase                         " search
set magic                                                           " regular expression
set linespace=0
set wildmenu
set wildmode=longest,list,full                                      " completion mode that is used for the character
set noerrorbells novisualbell visualbell                            " ╮ Turn off
set belloff=all                                                     " ├ beep/flash
set t_vb=                                                           " ╯ error beep/flash
" set list listchars=tab:\→\ ,tab:▸,trail:·,extends:»,precedes:«,nbsp:·,eol:¬
set list
set listchars=tab:\→\ ,trail:·,extends:»,precedes:«,nbsp:·
set cursorline                                                      " highlight the current line
set cursorcolumn
set guicursor=a:hor10-Cursor-blinkon0
set guicursor+=i-r-c-ci-cr-o:hor10-iCursor-blinkon0
set guicursor+=n:hor10-Cursor-blinkwait700-blinkon400-blinkoff250
set guicursor+=v-ve:block-Cursor
set virtualedit=onemore                                             " allow for cursor beyond last character
set scrolloff=3                                                     " scroll settings
set sidescroll=1
set sidescrolloff=5
set imcmdline                                                       " fix context menu messing
set complete+=kspell
set completeopt=longest,menuone                                     " supper tab
set foldenable                                                      " enable fold
set foldcolumn=1
set foldexpr=1                                                      " shown line number after fold
set foldlevel=100                                                   " not fold while vim set up
set shortmess+=filmnrxoOtTc                                         " abbrev. of messages (avoids 'hit enter')
set viewoptions=folds
set backspace=indent,eol,start                                      " make backspace h, l, etc wrap to
set whichwrap+=<,>,h,l
set go+=a                                                           " visual selection automatically copied to the clipboard
set hidden                                                          " switch between buffers with unsaved change
set equalalways
set formatoptions=tcrqn
set formatoptions+=rnmMB                                            " remove the backspace for combine lines (only for chinese)
set matchpairs+=<:>
" set autowrite
if has('cmdline_info')
  set ruler                                                         " ruler: show line and column number
  set showcmd                                                       " show (partial) command in status line
endif
if has('statusline')
  set laststatus=2                                                  " set status bar
  set statusline=%#User2#%m%r%*\ %F\ %y,%{&fileformat}
  " set statusline+=\ %{FugitiveStatusline()}                       " set statusline+=\ %{fugitive#statusline()}
  set statusline+=%=\ %-{strftime(\"%H:%M\ %d/%m/%Y\")}\ %b[A],0x%B\ %c%V,%l/%L\ %1*--%n%%--%*\ %p%%\ |
endif
" set synmaxcol=128
" set binary
set exrc
set secure

if has('persistent_undo') | set noundofile            | endif
if version > 74399        | set cryptmethod=blowfish2 | endif


" /**************************************************************
"      _                _             _
"  ___| |__   ___  _ __| |_ ___ _   _| |_
" / __| '_ \ / _ \| '__| __/ __| | | | __|
" \__ \ | | | (_) | |  | || (__| |_| | |_
" |___/_| |_|\___/|_|   \__\___|\__,_|\__|
"
" **************************************************************/
" :help map-overview : https://vimhelp.org/map.txt.html#map-overview
noremap <leader>v    :e ~/.vimrc<CR>
noremap <F1>         <ESC>
inoremap <F1>        <ESC>a
nnoremap j           gj
nnoremap gj          j
nnoremap k           gk
nnoremap gk          k
nnoremap n           nzzzv
nnoremap N           Nzzzv
nnoremap <leader>bd  :bd<CR>
nnoremap <C-k>       <C-w>k
nnoremap <C-j>       <C-w>j
" nnoremap <C-l>     <C-w>l                                         " conflict with redraw shortcut : https://vimhelp.org/various.txt.html#CTRL-L
nnoremap <C-h>       <C-w>h
nnoremap <C-a>       <ESC>^
inoremap <C-a>       <ESC>I
cnoremap <C-a>       <Home>
nnoremap <C-e>       <ESC>$
inoremap <C-e>       <ESC>A
cnoremap <C-e>       <End>
nnoremap Y           y$
nnoremap <Del>       "_x
xnoremap <Del>       "_d
nnoremap <space>     za
nnoremap &           :&&<CR>
xnoremap &           :&&<CR>
vnoremap s           <Plug>VSurround
vnoremap //          y/\V<C-R>=escape(@",'/\')<CR><CR>

cnoreabbrev W        w
cnoreabbrev W!       w!
cnoreabbrev Q        q
cnoreabbrev Q!       q!
cnoreabbrev X        x
cnoreabbrev X!       x!
cnoreabbrev XA       xa
cnoreabbrev XA!      xa!
cnoreabbrev WQ       wq
cnoreabbrev WQ!      wq!
cnoreabbrev QA       qa
cnoreabbrev QA!      qa!
cnoreabbrev WA       wa
cnoreabbrev WA!      wa!
cnoreabbrev NOH      noh
cnoreabbrev Noh      noh
cnoreabbrev %Y       %y
cnoreabbrev %D       %d
cnoremap sudow!!     w !sudo tee > /dev/null %
cnoremap sw!!        execute 'silent! write !sudo tee % >/dev/null' <bar> edit!
" cnoremap lss       lss<cr>:b<space>
" cnoremap lsd       lss<cr>:bd<space>
" cnoremap redr      redraw!

inoremap <leader>tt  <C-R>=strftime("%d/%m/%y %H:%M:%S")<cr>
inoremap <leader>fn  <C-R>=expand("%:t:r")<CR>
inoremap <leader>fe  <C-R>=expand("%:t")<CR>
inoremap <leader>w   <C-O>:w<CR>
nnoremap <leader>G   :%s///gn<CR>
nnoremap <leader>idl :IndentLineEnable<CR>

nnoremap <leader>zil :g/^/ s//\=line('.').' '/<CR>                  " [i]nsert [l]ine number
nnoremap <leader>zcm :%s/<C-v><CR>/\r/g<CR>                         " [c]onvert [m] to new line
nnoremap <leader>zdm :%s/<C-v><CR>//ge<CR>                          " [d]elete [m]()
nnoremap <leader>zdb :%s/\s\+$//<CR>                                " [d]elete trailing space ( [b]lank )
nnoremap <leader>zbl :g/^\s*$/d<CR>                                 " [d]elete [b]lank [l]ine
nnoremap <leader>zd2 :%s/​//g<CR>                              " [d]elete <200b>
nnoremap <leader>zdd :%s/ / /g<CR>                                  " [d]elete [d]ot(• )
nnoremap <leader>zds :%s/^<span.*span>//g<CR>                       " [d]elete [s]pan tag
nnoremap <leader>zdi :%s/^\s\+//<CR>                                " [d]elete [i]ndent spaces
nnoremap <leader>zid i•<ESC>                                        " [i]nsert [d]ot(•)
" cacular expr
nnoremap <leader>cr  0yt=a<c-r>=<c-r>"<cr><esc>
" cacular expr
nnoremap <leader>*   *<C-O>:%s///gn<CR>
" cacular the matches numbers ( [w]c -[l] )
nnoremap <leader>zwl :%s///gn<CR>

" https://vim.fandom.com/wiki/Capitalize_words_and_regions_easily
" if ( &tildeop )
"   nnoremap gcw  guw~l
"   nnoremap gcW  guW~l
"   nnoremap gciw guiw~l
"   nnoremap gciW guiW~l
"   nnoremap gcis guis~l
"   nnoremap gc$  gu$~l
"   nnoremap gcgc guu~l
"   nnoremap gcc  guu~l
"   vnoremap gc   gu~l
" else
"   nnoremap gcw  guw~h
"   nnoremap gcW  guW~h
"   nnoremap gciw guiw~h
"   nnoremap gciW guiW~h
"   nnoremap gcis guis~h
"   nnoremap gc$  gu$~h
"   nnoremap gcgc guu~h
"   nnoremap gcc  guu~h
"   vnoremap gc   gu~h
" endif
nnoremap gcc :s/\v<(.)(\w*)/\u\1\L\2/g<CR>
nnoremap gcgc gcc

iabbrev <leader>/*   /*********************************
iabbrev <leader>*/   *********************************/
iabbrev <leader>#-   #------------------

" /**************************************************************
"        _             _                  _   _   _
"  _ __ | |_   _  __ _(_)_ __    ___  ___| |_| |_(_)_ __   __ _ ___
" | '_ \| | | | |/ _` | | '_ \  / __|/ _ \ __| __| | '_ \ / _` / __|
" | |_) | | |_| | (_| | | | | | \__ \  __/ |_| |_| | | | | (_| \__ \
" | .__/|_|\__,_|\__, |_|_| |_| |___/\___|\__|\__|_|_| |_|\__, |___/
" |_|            |___/                                    |___/
"
" **************************************************************/
let g:auto_save                 = 0                                 " enable AutoSave on Vim startup

let g:ctrlp_map                 = '<c-p>'                           " CtrlP
let g:ctrlp_working_path_mode   = 'ra'                              " search parents as well (stop searching safety)
let g:ctrlp_max_height          = 8
let g:ctrlp_max_depth           = 100
let g:ctrl_root_makers          = ['.ctrlp']                        " stop search if these files present
let g:ctrlp_use_caching         = 1
let g:ctrlp_clear_cache_on_exit = 0                                 " cross session caching
if has('win32') || has('win95') || has('win64')
  let g:ctrlp_cache_dir = $VIM . '/cache/ctrlp'
else
  let g:ctrlp_cache_dir = '$HOME/.vim/cache/ctrlp'
endif
let g:ctrlp_custom_ignore = {
    \ 'dir' : '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(exe|so|dll|rpm|tar|gz|bz2|zip|ctags|tags)|tags|ctags$',
    \ 'link': 'some_bad_symbolic_links',
    \ }

let g:EnhCommentifyAlignRight      = 'Yes'
let g:EnhCommentifyRespectIndent   = 'yes'
let g:EnhCommentifyPretty          = 'Yes'
let g:EnhCommentifyMultiPartBlocks = 'Yes'
let g:EnhCommentifyUseSyntax       = 'Yes'

noremap <leader>aid :AuthorInfoDetect<CR>
let g:vimrc_author = 'marslo'
let g:vimrc_email  = 'marslo.jiao@gmail.com'
" autocmd BufWritePre, FileWritePre * :AuthorInfoDetect<CR>
" autocmd BufWritePre               * :AuthorInfoDetect<CR>

noremap <leader>re :MRU<CR>                                         " most recently used(mru)
let MRU_Auto_Close    = 1
let MRU_Max_Entries   = 10
let MRU_Exclude_Files = '^/tmp/.*\|^/temp/.*\|^/media/.*\|^/mnt/.*'

noremap <Leader>u :GundoToggle<CR>
set undodir=~/.vim/undo/
set undofile

" for i in '75' '147' '108' '196' '208' '66' '106' '172' '115' '129'; do echo -e "\e[38;05;${i}m${i}"; done | column -c 250 -s ' '; echo -e "\e[m"
let g:rainbow_active    = 1
let g:rainbow_operators = 1
let g:rainbow_conf      = {
\   'guifgs' : [ '#6A5ACD', '#ff6347', '#b58900', '#9acd32', '#EEC900', '#9A32CD', '#EE7600', '#268bd2', '#183172' ],
\   'ctermfgs' : 'xterm-256color' == $TERM ? [ '75', '147', '108', '196', '208', '66', '106', '172', '115', '129' ] : [ 'lightblue', 'lightgreen', 'yellow', 'red', 'magenta' ],
\   'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
\   'separately': {
\     '*': {},
\     'markdown': {
\       'parentheses_options': 'containedin=markdownCode contained',
\     },
\     'css': {
\       'parentheses': [['(',')'], ['\[','\]']],
\     },
\     'scss': {
\       'parentheses': [['(',')'], ['\[','\]']],
\     },
\     'html': {
\       'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
\     },
\     'stylus': {
\       'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup'],
\     }
\   }
\}

let g:indentLine_enabled              = 1
let g:indentLine_color_gui            = "#282828"
let g:indentLine_color_term           = 239
let g:indentLine_indentLevel          = 20
let g:indentLine_showFirstIndentLevel = 1
let g:indentLine_color_tty            = 0
let g:indentLine_faster               = 1
let g:indentLine_concealcursor        = 'inc'
let g:indentLine_conceallevel         = 2
let g:indentLine_char                 = '¦'

let g:AutoPairs        = {'(':')', '[':']', '{':'}', '<':'>',"'":"'",'"':'"', '`':'`'}
let g:AutoPairsParens  = {'(':')', '[':']', '{':'}', '<':'>'}
let g:AutoPairsFlyMode = 0
let g:AutoPairsShortcutBackInsert = '<M-b>'

" gabrielelana/vim-markdown
" nnoremap <Leader>cc :let &cole=(&cole == 2) ? 0 : 2 <bar> echo 'conceallevel ' . &cole <CR>
" let g:vim_markdown_folding_style_pythonic = 1
" let g:vim_markdown_override_foldtext      = 0
" let g:vim_markdown_autowrite              = 1
" let g:vim_markdown_new_list_item_indent   = 4
" let g:vim_markdown_toc_autofit            = 1
" let g:vim_markdown_conceal                = 0
"" set conceallevel                         = 2
" let g:vim_markdown_frontmatter            = 1
" let g:vim_markdown_json_frontmatter       = 1
" let g:markdown_enable_spell_checking      = 0
" let g:markdown_enable_input_abbreviations = 0
" let g:markdown_enable_conceal             = 0
" hi markdownItalic           guifg=gray25    gui=underline
" hi MarkdownHeadingDelimiter gui=bold        guifg=gray25
" hi htmlSpecialChar          guifg=black
" hi markdownBold             gui=bold        guifg=gray25
" hi markdownUrl              guifg=#2fb3a6
" hi markdownAutomaticLink    guifg=#2fb3a6
" hi markdownLinkText         guifg=#317849
" hi markdownUrlTitle         guifg=#317849
" hi markdownBlockquote       guifg=#317849   gui=bold
" hi markdownId               guifg=#2fb3a6
" hi markdownIdDeclaration    guifg=#317849   gui=bold
" hi markdownListMarker       guifg=#317849

" for tpope vim-markdown
" let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']
" let g:markdown_syntax_conceal = 0
" let g:markdown_minlines = 100

" preservim/vim-markdown
let g:vim_markdown_toc_autofit          = 1
let g:vim_markdown_conceal              = 0
let g:vim_markdown_conceal_code_blocks  = 0
let g:vim_markdown_strikethrough        = 1
let g:vim_markdown_folding_disabled     = 1                         " =1 to disable folding
let g:vim_markdown_new_list_item_indent = 2
" let g:vim_markdown_frontmatter        = 1
" let g:vim_markdown_json_frontmatter   = 1
" let g:vim_markdown_autowrite          = 1
" let g:vim_markdown_follow_anchor      = 1
" let g:vim_markdown_anchorexpr         = "'<<'.v:anchor.'>>'"

noremap <Leader>tm :TableModeToggle<CR>
let g:table_mode_corner          = '|'
let g:table_mode_header_fillchar = '-'
let g:table_mode_align_char      = ":"
let g:table_mode_corner          = "|"
let g:table_mode_align_char      = ":"
" let g:table_mode_corner_corner = '+'

" function! s:isAtStartOfLine(mapping)
"   let text_before_cursor = getline('.')[0 : col('.')-1]
"   let mapping_pattern = '\V' . escape(a:mapping, '\')
"   let comment_pattern = '\V' . escape(substitute(&l:commentstring, '%s.*$', '', ''), '\')
"   return (text_before_cursor =~? '^' . ('\v(' . comment_pattern . '\v)?') . '\s*\v' . mapping_pattern . '\v$')
" endfunction
" inoreabbrev <expr> <bar><bar>
"           \ <SID>isAtStartOfLine('\|\|') ?
"           \ '<c-o>:TableModeEnable<cr><bar><space><bar><left><left>' : '<bar><bar>'
" inoreabbrev <expr> __
"           \ <SID>isAtStartOfLine('__') ?
"           \ '<c-o>:silent! TableModeDisable<cr>' : '__'
" let g:tabular_loaded = 1

if exists( ":Tabularize" )
  noremap  <Leader>a= :Tabularize /=<CR>
  vnoremap <Leader>a= :Tabularize /=<CR>
  noremap  <leader>a: :Tabularize /:\zs<CR>
  vnoremap <leader>a: :Tabularize /:\zs<CR>
  inoremap <silent> <Bar>   <Bar><Esc>:call <SID>table_auto_align()<CR>
  function! s:table_auto_align()
    let p = '^\s*|\s.*\s|\s*$'
    if exists( ':Tabularize' ) && getline('.') =~# '^\s*|'
      \ && (getline(line('.')-1) =~# p || getline( line('.')+1 ) =~# p)
      let column   = strlen( substitute(getline('.')[0:col('.')],'[^|]','','g') )
      let position = strlen( matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*') )
      Tabularize/|/l1
      normal! 0
      call search( repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.') )
    endif
  endfunction
  command! -nargs=1 First exec 'Tabularize /^[^' . escape(<q-args>, '\^$.[?*~') . ']*\zs' . escape(<q-args>, '\^$.[?*~')
endif

" git
nnoremap <leader>mp  :execute 'silent !git mp' \| redraw!<CR>
nnoremap <Leader>ebb :<C-u>call gitblame#echo()<CR>
nnoremap <Leader>bb  :BlamerToggle<CR>                              " APZelos/blamer.nvim
let g:blamer_enabled              = 0
let g:blamer_delay                = 100
let g:blamer_show_in_visual_modes = 0
let g:blamer_show_in_insert_modes = 0
let g:blamer_relative_time        = 1
" let g:blamer_prefix             = ' » '

" nnoremap <leader>mp :silent exec '! git mp'<CR>
" fugitive
" nnoremap <Leader>ga :Git add %:p<CR><CR>
" nnoremap <Leader>gs :Gstatus<CR>
" nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
" nnoremap <leader>gp :Ggrep<Space>
" nnoremap <leader>gb :Git branch<Space>
" nnoremap <leader>go :Git checkout<Space>
" nnoremap <leader>gc :Git commit -am ""<Left>
" command! -bar -nargs=* Gpull execute 'Git pull'
" command! -bar -nargs=* Gpush execute 'Git push'

" gitgutter
nnoremap <leader>d :GitGutterFold<CR>
let g:gitgutter_git_executable = '/usr/local/bin/git'
let g:gitgutter_enabled        = 1
let g:gitgutter_realtime       = 0
let g:gitgutter_eager          = 0
set updatetime=250
set signcolumn=yes
" highlight clear LineNr
highlight clear SignColumn

" snippet
imap <S-C-J> <Plug>snipMateNextOrTrigger
smap <S-C-J> <Plug>snipMateNextOrTrigger
imap <Tab>   <Plug>snipMateNextOrTrigger

let g:plist_display_format       = 'xml'
let g:plist_json_filetype        = 'javascript'

let g:signify_disable_by_default = 0
let g:signify_vcs_list           = [ 'git' ]

" tabnine-vim                                                        " Plugin 'codota/tabnine-vim'
" if index(['vim'], &filetype) == -1 | let g:loaded_youcompleteme = 1 | endif
" if !( &filetype == 'vim' ) | let g:loaded_youcompleteme = 1 | endif

" ycm
" let g:ycm_key_invoke_completion='<C-S-Space>'
nnoremap <leader>gc :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>gf :YcmCompleter GoToDefinition<CR>
nnoremap <leader>gg :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <leader>gd :YcmDiags<CR>
" set completeopt-=preview
let g:ycm_server_keep_logfiles                    = 1
let g:ycm_server_log_level                        = 'debug'
let b:ycm_largefile                               = 1
let g:ycm_cache_omnifunc                          = 0
let g:ycm_confirm_extra_conf                      = 0
let g:ycm_python_binary_path                      = '/usr/local/opt/python/libexec/bin/python'
let g:ycm_extra_conf_globlist                     = [ '~/dev/*','!~/*' ]
let g:ycm_complete_in_comments                    = 1
let g:ycm_server_keep_logfiles                    = 1
let g:ycm_key_invoke_completion                   = '<C-\>'
" let g:ycm_global_ycm_extra_conf                   = '~/.marslo/.ycm/global_extra_conf.py'
let g:ycm_seed_identifiers_with_syntax            = 1
let g:ycm_always_populate_location_list           = 1
let g:ycm_min_num_of_chars_for_completion         = 1
let g:ycm_disable_for_files_larger_than_kb        = 1000
let g:ycm_collect_identifiers_from_tags_files     = 1
let g:ycm_filetype_specific_completion_to_disable = { 'gitcommit': 1, 'vim': 1 }
let g:ycm_semantic_triggers =  {
  \   'c': ['->', '.'],
  \   'objc': ['->', '.', 're!\[[_a-zA-Z]+\w*\s', 're!^\s*[^\W\d]\w*\s',
  \            're!\[.*\]\s'],
  \   'ocaml': ['.', '#'],
  \   'cpp,cuda,objcpp': ['->', '.', '::'],
  \   'perl': ['->'],
  \   'php': ['->', '::'],
  \   'cs,d,elixir,go,groovy,java,javascript,julia,perl6,python,scala,typescript,vb': ['.'],
  \   'ruby,rust': ['.', '::'],
  \   'lua': ['.', ':'],
  \   'erlang': [':'],
  \ }

"""" ycm for python
let g:ycm_python_interpreter_path = ''
let g:ycm_python_sys_path         = []
let g:ycm_extra_conf_vim_data     = [ 'g:ycm_python_interpreter_path', 'g:ycm_python_sys_path' ]

" ycm-core/lsp-examples
let g:ycm_lsp_dir          = '/Users/marslo/.vim/bundle/lsp-examples'
let s:pip_os_dir           = 'bin'
if has('win32') | let s:pip_os_dir = 'Scripts' | end
let g:ycm_language_server  = []
let g:ycm_language_server += [
  \   {
  \     'name': 'bash',
  \     'cmdline': [ 'node', expand( g:ycm_lsp_dir . '/bash/node_modules/.bin/bash-language-server' ), 'start' ],
  \     'filetypes': [ 'sh', 'bash' ],
  \   },
  \ ]
let g:ycm_language_server += [
  \   {
  \     'name': 'groovy',
  \     'cmdline': [ 'java', '-jar', expand( g:ycm_lsp_dir . '/groovy/groovy-language-server/build/libs/groovy-language-server-all.jar' ) ],
  \     'filetypes': [ 'groovy' ]
  \   },
  \ ]
let g:ycm_language_server += [
  \   {
  \     'name': 'json',
  \     'cmdline': [ 'node', expand( g:ycm_lsp_dir . '/json/node_modules/.bin/vscode-json-languageserver' ), '--stdio' ],
  \     'filetypes': [ 'json' ],
  \     'capabilities': { 'textDocument': { 'completion': { 'completionItem': { 'snippetSupport': v:true } } } },
  \   },
  \ ]
let g:ycm_language_server += [
  \   {
  \     'name': 'cmake',
  \     'cmdline': [ expand( g:ycm_lsp_dir . '/cmake/venv/' . s:pip_os_dir . '/cmake-language-server' )],
  \     'filetypes': [ 'cmake' ],
  \   },
  \ ]
let g:ycm_language_server += [
  \   {
  \     'name': 'python',
  \     'cmdline': [ 'node', expand( g:ycm_lsp_dir . '/python/node_modules/.bin/pyright-langserver' ), '--stdio' ],
  \     'filetypes': [ 'python' ],
  \   },
  \ ]
let g:ycm_language_server += [
  \   { 'name': 'vim',
  \     'filetypes': [ 'vim' ],
  \     'cmdline': [ expand( g:ycm_lsp_dir . '/viml/node_modules/.bin/vim-language-server' ), '--stdio' ]
  \   },
  \ ]
let g:ycm_language_server += [
  \   {
  \     'name': 'yaml',
  \     'cmdline': [ 'node', expand( g:ycm_lsp_dir . '/yaml/node_modules/.bin/yaml-language-server' ), '--stdio' ],
  \     'filetypes': [ 'yaml' ],
  \     'capabilities': {
  \       'workspace': { 'configuration': v:true },
  \       'textDocument': {
  \         'completion': {
  \           'completionItem': { 'snippetSupport': v:true },
  \         }
  \       }
  \     },
  \   },
  \ ]
let g:ycm_language_server += [
  \   { 'name': 'docker',
  \     'filetypes': [ 'dockerfile' ],
  \     'cmdline': [ expand( g:ycm_lsp_dir . '/docker/node_modules/.bin/docker-langserver' ), '--stdio' ]
  \   },
  \ ]

" spell and grammars
let g:grammarous#languagetool_cmd = 'languagetool'
set thesaurus+=~/.vim/spell/dictionary/thesaurii.txt
set thesaurus+=~/.vim/spell/dictionary/mthesaur.txt
set dictionary=/usr/share/dict/words

" fastFold
nnoremap zuz <Plug>(FastFoldUpdate)
xnoremap <silent> <leader>iz :<c-u>FastFoldUpdate<cr>]z<up>$v[z<down>^
xnoremap <silent> <leader>az :<c-u>FastFoldUpdate<cr>]zV[z
let g:fastfold_savehook               = 1
let g:fastfold_fold_command_suffixes  = ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']

let g:markdown_folding                = 1
let g:rst_fold_enabled                = 1
let g:tex_fold_enabled                = 1
let g:vimsyn_folding                  = 'af'
let g:xml_syntax_folding              = 1
let g:javaScript_fold                 = 1
let g:sh_fold_enabled                 = 7
let g:zsh_fold_enable                 = 1
let g:ruby_fold                       = 1
let g:perl_fold                       = 1
let g:perl_fold_blocks                = 1
let g:r_syntax_folding                = 1
let g:rust_fold                       = 1
let g:php_folding                     = 1
let g:fortran_fold                    = 1
let g:clojure_fold                    = 1
let g:baan_fold                       = 1

" vim-yaml-folds
set foldlevelstart=20

" syntastic settings                                                " Plugin 'vim-syntastic/syntastic'
set statusline+=%#warningmsg#
set statusline+=\ %{SyntasticStatuslineFlag()}
set statusline+=\ %* |
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_check_on_wq              = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_loc_list_height          = 2
let g:syntastic_ignore_files             = ['\.py$']
let g:syntastic_html_tidy_ignore_errors  = [" proprietary attribute \"ng-"]
let g:syntastic_enable_signs             = 1
let g:syntastic_info_symbol              = 'ϊ'                      " ࠵ ೲ
let g:syntastic_error_symbol             = '✗'                      " ஓ ௐ ྾
let g:syntastic_warning_symbol           = '⍨'                      " ᓆ ᓍ 𐘿
let g:syntastic_style_error_symbol       = '⍥'
let g:syntastic_style_warning_symbol     = 'ఠ'                      " ⍤ ൠ
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
highlight link SyntasticErrorSign        Error
highlight link SyntasticWarningSign      GruvboxYellow
highlight link SyntasticStyleErrorSign   GruvboxRedSign
highlight link SyntasticStyleWarningSign GruvboxPurpleSign

" yamllint                                                          " brew install yamllint
set foldlevelstart=20                                               " vim-yaml-folds
" ale                                                               " :help g:ale_echo_msg_format
let g:ale_echo_msg_format                 = '[%linter%] %code%: %s [%severity%] '
let g:ale_virtualtext_prefix              = '%comment% %type% [%code%]: '
let g:ale_sign_error                      = '💢'                    " ✘ 👾 💣  🙅 🤦
let g:ale_sign_warning                    = 'ᑹᑹ'                    " ⚠ ⸮ ⸘ ☹
let g:ale_sign_info                       = 'ᓆ'                     " ⸚ ϔ 𐘿 𐰦
let g:ale_sign_style_error                = '⍥'                     " ᑹ
let g:ale_sign_style_warning              = 'ᓍ'                     " ᓏ
let g:ale_lint_on_text_changed            = 'never'
let g:ale_fix_on_save                     = 0
let g:ale_lint_on_save                    = 1
let g:ale_lint_on_text_changed            = 'never'
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace  = 1
let g:ale_hover_to_preview                = 1
let g:ale_floating_preview                = 1
let g:ale_close_preview_on_insert         = 1

" call matchadd('ColorColumn', '\%81v', 100)
" match OverLength /\%81v.\+/

augroup collumnLimit
  set colorcolumn=80
  highlight CollumnLimit    guibg=NONE    guifg=#4e4e4e    ctermfg=240
  autocmd!
  let collumnLimit = 80
  let pattern      = '\%<' . ( collumnLimit+1 ) . 'v.\%>' . collumnLimit . 'v'
  let w:m1         = matchadd( 'CollumnLimit', pattern, -1 )
augroup END

" /**************************************************************
"              _                           _
"   __ _ _   _| |_ ___   ___ _ __ ___   __| |
"  / _` | | | | __/ _ \ / __| '_ ` _ \ / _` |
" | (_| | |_| | || (_) | (__| | | | | | (_| |
"  \__,_|\__,_|\__\___/ \___|_| |_| |_|\__,_|
"
" **************************************************************/
if has( "autocmd" )
  autocmd BufRead,BufNewFile *.t              set filetype=perl
  autocmd BufRead,BufNewFile *.ltsv           set filetype=ltsv syntax=groovy noexpandtab
  autocmd BufEnter           *.md             exe 'noremap <F5> :!"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" %:p "--no-gpu"<CR>'
  autocmd BufEnter           *.markdown       exe 'noremap <F5> :!"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --no-gpu"  %:p<CR>'
  " autocmd BufWinLeave      *                silent! mkview
  autocmd BufWinEnter        *                silent! loadview
  autocmd QuickFixCmdPost    *grep*           cwindow
  autocmd Syntax       *                      syn match ExtraWhitespace /\s\+$\| \+\ze\t/
  autocmd Syntax       c,cpp,python,vim,xml,html,xhtml,vim,groovy,Jenkinsfile,yaml normal zM
  autocmd Syntax       c,cpp,python,vim,xml,html,xhtml,vim,groovy,Jenkinsfile,yaml let g:indentLine_loaded=1
  autocmd Syntax       groovy,Jenkinsfile,python                                   setlocal foldmethod=indent
  " https://vim.fandom.com/wiki/Syntax_folding_for_Java
  autocmd FileType     java                   setlocal foldmarker=/**,**/ foldmethod=marker foldcolumn=1
  autocmd FileType     make,snippet,robot     setlocal tabstop=4 softtabstop=4 shiftwidth=4
  autocmd FileType     yaml                   setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
  autocmd FileType     javascript             syntax   clear jsFuncBlock  " rainbow issue #2
  autocmd BufEnter     *                      if &diff         | let g:blamer_enabled=0 | endif    " ╮ disable git blame in diff mode
  autocmd BufEnter     *                      if ! empty(&key) | let g:blamer_enabled=0 | endif    " ╯ and encrypt mode
  autocmd BufWritePre  *\(.ltsv\|.diffs\)\@<! silent! retab!              " automatic retab: https://vim.fandom.com/wiki/Remove_unwanted_spaces
  autocmd BufWritePre  *                      %s/\s\+$//e | %s/\r$//e     " automatic remove trailing space
  autocmd BufWritePost *\(.md\)               silent :DocToc              " automatic build doctoc when save it
  " autocmd BufWritePre                                         *.html :normal gg=G
  " autocmd BufWritePre,BufWritePost,FileWritePre,FileWritePost *      silent :redraw!

  augroup DevOps
    autocmd BufRead,BufNewFile *                                   setfiletype jenkinsfile
    autocmd FileType           groovy,Jenkinsfile,json,sh,markdown set tabstop=2 softtabstop=2 shiftwidth=2
    autocmd FileType           vim                                 let g:ycm_confirm_extra_conf = 1
    if index( ['README', 'SUMMARY'], expand("%:r") ) == -1
      autocmd BufWritePost     *\(.md\)            silent :DocToc             " automatic build doctoc when save it
    endif
    autocmd BufNewFile,BufRead                                                " git config files
          \ *.git/config,.gitconfig,.gitmodules,gitconfig
          \,~/.marslo/.gitalias
          \ setfiletype gitconfig

    " autocmd Syntax                         groovy,Jenkinsfile :IndentLinesEnable
    " autocmd BufReadPost                    Jenkinsfile        set filetype=groovy syntax=groovy
    " autocmd BufNewFile,BufRead             Jenkinsfile        setf groovy
    " autocmd BufNewFile,BufRead,BufReadPost Jenkinsfile        setlocal foldmethod=indent
    " autocmd FileType                       Jenkinsfile        setlocal filetype=groovy syntax=groovy foldmethod=indent
    " autocmd FileType                       Jenkinsfile        set syntax=groovy filetype=groovy

    if did_filetype()                     | finish      | endif
    if getline(1) =~ '^#!.*[/\\]groovy\>' | setf groovy | endif               " to setup filetype to groovy if first line matches `#!.*[/\\]groovy`
  augroup END

  augroup ShellScript
    autocmd!
    autocmd   Syntax       bash           set filetype=sh
    autocmd   FileType     sh,bash,shell  silent :retab!
    autocmd!  BufWritePre  *.sh           silent :retab!                      " automatic retab
    autocmd!  BufWritePost *.sh           silent :redraw!                     " automatic redraw for shellcheck
    " autocmd BufWritePost *.sh           !chmod +x %
    " autocmd BufWritePre,BufWritePost *.sh call DoRedraw()
  augroup END

  augroup Python
    autocmd BufNewFile,BufRead python
            \ set tabstop=2 softtabstop=2 shiftwidth=2
            \ setlocal shiftwidth=2 tabstop=2 softtabstop=2 autoindent
            \ fileformat=unix
    autocmd FileType python syntax keyword pythonDecorator print self
    autocmd FileTYpe python set isk-=.
  augroup END

  augroup vimrc
    autocmd! BufWritePost ~/.vimrc silent! source %
    autocmd  BufReadPre   *        setlocal foldmethod=indent
    autocmd  BufWinEnter  *        if &fdm == 'indent' | setlocal foldmethod=manual | endif
  augroup END

  " autocmd FileType qf call AdjustWindowHeight(3, 10)
  " function! AdjustWindowHeight(minheight, maxheight)
    " exe max([min([line("$"), a:maxheight]), a:minheight]) . "wincmd _"
  " endfunction

  " skip quickfix : https://vi.stackexchange.com/a/16709/7389
  augroup TermIgnore                                                          " skip quickfix : https://vi.stackexchange.com/a/16709/7389
    autocmd!
    autocmd TerminalOpen * set nobuflisted
  augroup END

  if version > 703
    " autocmd FocusLost * set norelativenumber
    autocmd FocusGained * set relativenumber
    autocmd InsertEnter * set norelativenumber
    autocmd InsertLeave * set relativenumber
    autocmd CmdwinEnter * set norelativenumber
    autocmd CmdwinLeave * set relativenumber
    autocmd CmdwinEnter * let b:ei_save = &eventignore | set eventignore=CursorHold,InsertEnter
    autocmd CmdwinLeave * let &eventignore = b:ei_save
  endif

  augroup CustomTabularize
    autocmd!
    " https://github.com/jwhitley/vimrc/blob/master/.vimrc
    " autocmd VimEnter * if exists(":Tabularize") | exe ":AddTabularPattern! bundles /[^ ]\\+\\//l1r0" | endif
    " add for plugin/TabularMaps.vim
    autocmd VimEnter * if exists(":Tabularize") | exe ":AddTabularPattern 1,  /^[^,]*\zs,/r1c1l0" | endif
    autocmd VimEnter * if exists(":Tabularize") | exe ":AddTabularPattern 1=  /^[^=]*\zs="        | endif
    autocmd VimEnter * if exists(":Tabularize") | exe ":AddTabularPattern 1== /^[^=]*\zs=/r1c1l0" | endif
  augroup END

endif

let g:fzf_colors = {
  \ 'fg':         ['fg', 'Normal'],
  \ 'bg':         ['bg', 'Normal'],
  \ 'preview-bg': ['bg', 'NormalFloat'],
  \ 'hl':         ['fg', 'Comment'],
  \ 'fg+':        ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':        ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':        ['fg', 'Statement'],
  \ 'info':       ['fg', 'PreProc'],
  \ 'border':     ['fg', 'Ignore'],
  \ 'prompt':     ['fg', 'Conditional'],
  \ 'pointer':    ['fg', 'Exception'],
  \ 'marker':     ['fg', 'Keyword'],
  \ 'spinner':    ['fg', 'Label'],
  \ 'header':     ['fg', 'Comment']
  \ }

highlight SpellBad        term=underline   cterm=underline     ctermbg=0
highlight ExtraWhitespace ctermbg=red      guibg=red
highlight DiffText        term=reverse     cterm=reverse       ctermfg=109      ctermbg=235 gui=reverse guifg=#fabd2f guibg=#458588
" highlight Cursor        guifg=white      guibg=gray          gui=bold
" highlight iCursor       guifg=white      guibg=steelblue     gui=underline

" vim:tabstop=2:softtabstop=2:shiftwidth=2:expandtab:filetype=vim:foldmethod=marker:foldmarker="\ **************************************************************/,"\ /**************************************************************
